### ISSUE TITLE
HTTP POST does not work!

### ISSUE THREAD

**Issue by mepa1363** [ldesousa/pywps-4-demo#1]
I tried to make the HTTP POST working on this demo but no luck yet. It returns HTTP Error 400: BAD REQUEST. Any help would be appreciated.

**Comment by ldesousa** [comment]
Can you post here the request? You could get a 500 or a 405, but a 400 I can not replicate.

**Comment by mepa1363** [comment]
I tried `GetCapabilities`, `DescribeProcess`, and `Execute` requests, for example:
```
<wps:GetCapabilities xmlns:ows="http://www.opengis.net/ows/1.1" xmlns:wps="http://www.opengis.net/wps/1.0.0" xmlns:xlink="http://www.w3.org/1999/xlink" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:schemaLocation="http://www.opengis.net/wps/1.0.0 ../wpsGetCapabilities_request.xsd" language="en-CA" service="WPS">
    <wps:AcceptVersions>
        <ows:Version>1.0.0</ows:Version>
    </wps:AcceptVersions>
</wps:GetCapabilities>
```
I used the requests example from the OGC's schemas repository (http://schemas.opengis.net/wps/1.0.0/examples/)
